export interface StyleConfig {
  id: string
  name: string
  slug: string
  emoji: string
  description: string
  longDescription: string
  image: string
  tags: string[]
  hot?: boolean
  faqs: { q: string; a: string }[]
  metaTitle: string
  metaDescription: string
}

export const styles: StyleConfig[] = [
  {
    id: 'ghibli',
    name: 'Studio Ghibli',
    slug: 'ghibli',
    emoji: '🌸',
    description: 'Studio Ghibli anime style',
    longDescription: 'Transform your photos into enchanting Studio Ghibli-inspired artwork. Capture the warm, hand-painted aesthetic of Hayao Miyazaki\'s beloved films — soft watercolour skies, dreamy lighting, and that unmistakable whimsical charm. Perfect for profile pictures, gifts, and social media.',
    image: '/examples/ghibli.jpg',
    tags: ['anime', 'ghibli', 'miyazaki', 'watercolour', 'dreamy'],
    hot: true,
    metaTitle: 'Ghibli AI Art Style — Transform Photos into Studio Ghibli Art | MyMeme',
    metaDescription: 'Turn any photo into stunning Studio Ghibli-style art in seconds. AI-powered Ghibli filter with Miyazaki\'s signature warm, dreamy aesthetic. Try free!',
    faqs: [
      { q: 'What is the Ghibli art style?', a: 'The Ghibli art style is inspired by Studio Ghibli\'s iconic anime films like Spirited Away, My Neighbour Totoro, and Howl\'s Moving Castle. It features soft watercolour tones, warm lighting, and a magical, hand-painted quality.' },
      { q: 'Does the Ghibli filter preserve my face?', a: 'Yes! Our AI carefully preserves your facial features and likeness while applying the Ghibli aesthetic — you\'ll still look like you, just in Miyazaki\'s world.' },
      { q: 'Can I use Ghibli-style photos on social media?', a: 'Absolutely! Ghibli-style profile pictures are hugely popular on Instagram, TikTok, and Twitter. All generated images are yours to use however you like.' },
      { q: 'How long does the Ghibli transformation take?', a: 'Just 10-15 seconds. Upload your photo, select Ghibli, and watch the magic happen in real time.' },
    ],
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    slug: 'cyberpunk-neon',
    emoji: '🌃',
    description: 'Futuristic neon cyberpunk vibes',
    longDescription: 'Dive into a neon-drenched future with our Cyberpunk style. Your photos get transformed with electric blues, hot pinks, and glowing neon highlights against dark, atmospheric backgrounds. Think Blade Runner meets your selfie — gritty, cinematic, and utterly cool.',
    image: '/examples/cyberpunk-neon.jpg',
    tags: ['cyberpunk', 'neon', 'futuristic', 'sci-fi', 'blade runner'],
    hot: true,
    metaTitle: 'Cyberpunk Neon AI Filter — Turn Photos into Cyberpunk Art | MyMeme',
    metaDescription: 'Transform photos into stunning cyberpunk neon art. Electric blues, hot pinks, and Blade Runner vibes. AI-powered, instant results. Try free!',
    faqs: [
      { q: 'What does the Cyberpunk filter do?', a: 'It transforms your photo with neon lighting, futuristic colour grading, and a dark atmospheric background — like you\'re living in a Blade Runner-style future city.' },
      { q: 'Does it work with group photos?', a: 'It works best with individual portraits or selfies. For group photos, results may vary.' },
      { q: 'Can I adjust the neon intensity?', a: 'The AI automatically optimises the neon effect for your photo. Each result is unique to the input image.' },
      { q: 'What resolution are the results?', a: 'All transformations are delivered at HD 1024×1024 resolution, perfect for social media and prints.' },
    ],
  },
  {
    id: 'renaissance',
    name: 'Renaissance',
    slug: 'renaissance',
    emoji: '🏛️',
    description: 'Classical master painting',
    longDescription: 'Step into a masterpiece. Our Renaissance style transforms you into a subject worthy of the Louvre — rich oil tones, dramatic chiaroscuro lighting, and the gravitas of a 16th-century portrait. Perfect for creating timeless, elegant artwork from any photo.',
    image: '/examples/renaissance.jpg',
    tags: ['renaissance', 'classical', 'oil painting', 'portrait', 'masterpiece'],
    hot: true,
    metaTitle: 'Renaissance AI Portrait — Classical Oil Painting Style | MyMeme',
    metaDescription: 'Transform your photo into a Renaissance masterpiece. Classical oil painting style with dramatic lighting. Museum-worthy AI art in seconds. Try free!',
    faqs: [
      { q: 'What is the Renaissance style?', a: 'Inspired by the great masters like Leonardo da Vinci and Rembrandt, this style gives your photo rich oil-painting textures, dramatic lighting, and the timeless elegance of classical portraiture.' },
      { q: 'Is it suitable for gifts?', a: 'Absolutely! Renaissance-style portraits make stunning printed gifts — frame them for birthdays, anniversaries, or just to impress.' },
      { q: 'Does it work with pet photos?', a: 'Yes! Pet Renaissance portraits are incredibly popular. Your dog or cat will look like royalty.' },
      { q: 'How accurate is the likeness?', a: 'Our AI preserves your key features while adding the Renaissance aesthetic. You\'ll be instantly recognisable in the artwork.' },
    ],
  },
  {
    id: 'oil-painting',
    name: 'Oil Painting',
    slug: 'oil-painting',
    emoji: '🖼️',
    description: 'Rich textured oil painting',
    longDescription: 'Experience the beauty of traditional oil painting without picking up a brush. Thick, textured brushstrokes, vibrant colours, and that unmistakable gallery-worthy finish. Every photo becomes a piece of fine art you\'d proudly hang on your wall.',
    image: '/examples/oil-painting.jpg',
    tags: ['oil painting', 'fine art', 'texture', 'brushstroke', 'gallery'],
    hot: true,
    metaTitle: 'Oil Painting AI Filter — Turn Photos into Oil Paintings | MyMeme',
    metaDescription: 'Transform any photo into a beautiful oil painting with AI. Rich textures, vibrant colours, gallery-worthy results. Instant and free to try!',
    faqs: [
      { q: 'How is Oil Painting different from Renaissance?', a: 'While Renaissance focuses on classical portraiture with dramatic lighting, Oil Painting emphasises visible brushstrokes, rich textures, and more vibrant, modern colour palettes.' },
      { q: 'Can I print the results?', a: 'Yes! The 1024×1024 HD output is perfect for printing up to A4 size. Many customers frame their oil painting transformations.' },
      { q: 'Does it work with landscapes?', a: 'Beautifully! Landscapes, cityscapes, and nature photos all look stunning in oil painting style.' },
      { q: 'How many credits does it cost?', a: 'Each transformation costs 1 credit. You get 3 free credits to start — no sign-up required.' },
    ],
  },
  {
    id: 'italian-brainrot',
    name: 'Italian Brainrot',
    slug: 'italian-brainrot',
    emoji: '🤌',
    description: 'Viral Italian meme style',
    longDescription: 'The viral meme style that broke the internet. Italian Brainrot transforms your photo into the absurd, over-the-top meme aesthetic that\'s taken TikTok and Twitter by storm. Exaggerated expressions, chaotic energy, and pure comedic gold. Perfect for memes and group chats.',
    image: '/examples/italian-brainrot.jpg',
    tags: ['meme', 'italian', 'brainrot', 'viral', 'tiktok', 'funny'],
    hot: true,
    metaTitle: 'Italian Brainrot AI Meme Filter — Viral TikTok Style | MyMeme',
    metaDescription: 'Create hilarious Italian Brainrot memes from any photo. The viral TikTok style everyone\'s talking about. AI-powered, instant. Try free!',
    faqs: [
      { q: 'What is Italian Brainrot?', a: 'Italian Brainrot is a viral meme aesthetic that originated on TikTok. It features exaggerated, absurd transformations with an Italian flair — think over-the-top expressions and chaotic comedic energy.' },
      { q: 'Will it make me look funny?', a: 'That\'s the whole point! Italian Brainrot is designed to be hilarious and shareable. Perfect for group chats and social media.' },
      { q: 'Is this style appropriate for professional use?', a: 'This one\'s purely for fun and memes! For professional use, try Renaissance, Oil Painting, or Ghibli.' },
      { q: 'Why is it called Brainrot?', a: 'It\'s internet slang for content that\'s so absurd it "rots your brain" — in the best possible way. It\'s a term of endearment in meme culture.' },
    ],
  },
  {
    id: 'anime',
    name: 'Anime',
    slug: 'anime',
    emoji: '⚡',
    description: 'Japanese anime style',
    longDescription: 'Transform yourself into an anime protagonist. Bold lines, vibrant colours, and expressive features bring your photo to life in authentic Japanese anime style. Whether you\'re a lifelong anime fan or just curious, the results are always stunning.',
    image: '/examples/anime.jpg',
    tags: ['anime', 'japanese', 'manga', 'cartoon', 'otaku'],
    metaTitle: 'Anime AI Filter — Transform Photos to Anime Style | MyMeme',
    metaDescription: 'Turn any photo into anime art with AI. Bold lines, vibrant colours, authentic Japanese anime style. Instant results. Try free!',
    faqs: [
      { q: 'What anime style does it create?', a: 'Our AI creates a modern anime aesthetic with bold lines, vibrant colours, and expressive features — similar to popular series like Demon Slayer or Jujutsu Kaisen.' },
      { q: 'Is it different from Ghibli?', a: 'Yes! While Ghibli is soft and watercolour-like, Anime style is bolder with sharper lines, more vivid colours, and a more action-oriented aesthetic.' },
      { q: 'Can I use it for my avatar?', a: 'Absolutely! Anime-style avatars are perfect for Discord, gaming profiles, and social media.' },
      { q: 'Does it work with full-body photos?', a: 'It works best with portraits and upper-body shots, but can handle full-body photos too.' },
    ],
  },
  {
    id: 'pixar',
    name: 'Pixar 3D',
    slug: 'pixar',
    emoji: '✨',
    description: 'Pixar-style animated character',
    longDescription: 'Become a Pixar character! Our AI transforms your photo into a charming 3D animated character with the warmth and personality of your favourite Pixar films. Big expressive eyes, smooth rendering, and that magical Pixar glow. Kids and adults love it equally.',
    image: '/examples/pixar.jpg',
    tags: ['pixar', '3d', 'animated', 'disney', 'cartoon'],
    metaTitle: 'Pixar 3D AI Filter — Turn Photos into Pixar Characters | MyMeme',
    metaDescription: 'Transform your photo into a Pixar-style 3D animated character. Charming, expressive, and magical. AI-powered, instant results. Try free!',
    faqs: [
      { q: 'Will I look like a real Pixar character?', a: 'Yes! The AI creates a 3D animated version of you with Pixar\'s signature warm lighting, smooth rendering, and expressive features. You\'ll be instantly recognisable.' },
      { q: 'Is it good for kids\' photos?', a: 'Kids absolutely love seeing themselves as Pixar characters! It\'s one of our most popular styles for children\'s photos.' },
      { q: 'Can I use it for couples?', a: 'Individual photos work best. For couples, try uploading each person separately for the best results.' },
      { q: 'What resolution is the output?', a: 'HD 1024×1024 — perfect for social media profiles and printing.' },
    ],
  },
  {
    id: 'caricature',
    name: 'Caricature',
    slug: 'caricature',
    emoji: '🎨',
    description: 'Fun exaggerated portrait',
    longDescription: 'Get the fairground caricature experience without the queue! Our AI exaggerates your most distinctive features in a playful, artistic way. Big grins, expressive eyes, and personality cranked up to eleven. Great for gifts and laughs.',
    image: '/examples/caricature.jpg',
    tags: ['caricature', 'cartoon', 'funny', 'exaggerated', 'portrait'],
    metaTitle: 'Caricature AI Filter — Fun Exaggerated Portraits | MyMeme',
    metaDescription: 'Turn photos into fun caricatures with AI. Exaggerated features, playful style. Perfect for gifts and laughs. Instant results. Try free!',
    faqs: [
      { q: 'How exaggerated will my features be?', a: 'The AI tastefully exaggerates your most distinctive features — it\'s playful and fun, never unflattering. Think theme park caricature artist, but digital.' },
      { q: 'Is it good for gifts?', a: 'Caricatures make brilliant personalised gifts! Print and frame them for birthdays, retirements, or just for fun.' },
      { q: 'Can I use a group photo?', a: 'Individual photos produce the best results. For groups, upload each person separately.' },
      { q: 'Does it work with pet photos?', a: 'Yes! Pet caricatures are adorable and very popular.' },
    ],
  },
  {
    id: 'gta',
    name: 'GTA V',
    slug: 'gta',
    emoji: '🔫',
    description: 'Grand Theft Auto loading screen',
    longDescription: 'Look like you belong on a GTA V loading screen. Bold outlines, saturated colours, and that iconic Rockstar Games aesthetic. One of the most requested styles — perfect for gamers, social media, and anyone who wants to look like a video game character.',
    image: '/examples/gta.jpg',
    tags: ['gta', 'gaming', 'rockstar', 'video game', 'loading screen'],
    metaTitle: 'GTA V AI Filter — Grand Theft Auto Style Photos | MyMeme',
    metaDescription: 'Turn your photo into a GTA V loading screen character. Bold outlines, iconic Rockstar aesthetic. AI-powered, instant. Try free!',
    faqs: [
      { q: 'Will it look like a real GTA loading screen?', a: 'Yes! The AI replicates the bold outlines, saturated colours, and stylised aesthetic of GTA V\'s iconic character art.' },
      { q: 'Is it popular?', a: 'GTA style is one of our top 5 most requested styles. Gamers and non-gamers alike love the bold, stylised look.' },
      { q: 'Can I use it as a gaming avatar?', a: 'Absolutely! GTA-style portraits make fantastic Steam, Xbox, PlayStation, and Discord profile pictures.' },
      { q: 'Does it work with full-body photos?', a: 'It works great with both portraits and full-body shots, just like real GTA character art.' },
    ],
  },
  {
    id: 'pop-art',
    name: 'Pop Art',
    slug: 'pop-art',
    emoji: '💥',
    description: 'Andy Warhol-style pop art',
    longDescription: 'Channel your inner Warhol. Bold colours, graphic contrasts, and the iconic pop art aesthetic that turned soup cans into fine art. Your photo gets the full pop art treatment — vibrant, bold, and gallery-ready.',
    image: '/examples/pop-art.jpg',
    tags: ['pop art', 'warhol', 'bold', 'graphic', 'colorful'],
    metaTitle: 'Pop Art AI Filter — Warhol-Style Photo Transformation | MyMeme',
    metaDescription: 'Transform photos into Andy Warhol-style pop art. Bold colours, graphic contrasts. AI-powered, instant results. Try free!',
    faqs: [
      { q: 'What is Pop Art style?', a: 'Inspired by Andy Warhol and Roy Lichtenstein, Pop Art uses bold colours, graphic contrasts, and simplified forms to create eye-catching, gallery-worthy artwork.' },
      { q: 'Will I get the multi-panel Warhol look?', a: 'The AI creates a single bold pop art portrait. You can generate multiple and arrange them yourself for the classic multi-panel effect.' },
      { q: 'Is it good for wall art?', a: 'Pop art prints look amazing on walls! The bold colours and graphic style really pop in larger formats.' },
      { q: 'Does it work with any photo?', a: 'Pop art style works best with clear, well-lit portraits. High-contrast photos produce the most striking results.' },
    ],
  },
  {
    id: 'watercolor',
    name: 'Watercolor',
    slug: 'watercolor',
    emoji: '🖌️',
    description: 'Soft artistic watercolour',
    longDescription: 'Delicate, ethereal, and beautiful. Our Watercolor style transforms your photos with soft, flowing paint effects, gentle colour bleeds, and that luminous quality unique to watercolour art. Perfect for elegant portraits and thoughtful gifts.',
    image: '/examples/watercolor.jpg',
    tags: ['watercolor', 'watercolour', 'soft', 'artistic', 'elegant'],
    metaTitle: 'Watercolor AI Filter — Soft Artistic Photo Transformation | MyMeme',
    metaDescription: 'Turn photos into beautiful watercolour art with AI. Soft, flowing paint effects, elegant results. Instant. Try free!',
    faqs: [
      { q: 'What makes the Watercolor style special?', a: 'It captures the delicate, luminous quality of real watercolour painting — soft colour bleeds, flowing brush effects, and an ethereal, elegant finish.' },
      { q: 'Is it good for wedding photos?', a: 'Watercolour-style wedding photos make absolutely gorgeous gifts and keepsakes. It adds a romantic, timeless quality.' },
      { q: 'How is it different from Oil Painting?', a: 'Watercolor is lighter, softer, and more translucent. Oil Painting is bolder with visible brush textures and richer colours.' },
      { q: 'Does it work with landscape photos?', a: 'Beautifully! Landscapes, flowers, and nature scenes look stunning in watercolour style.' },
    ],
  },
  {
    id: 'superhero',
    name: 'Superhero',
    slug: 'superhero',
    emoji: '🦸',
    description: 'Comic book superhero',
    longDescription: 'Unleash your inner superhero. Bold comic book styling, dynamic poses, and the unmistakable look of a Marvel or DC character. Whether it\'s for fun or a gift, seeing yourself as a superhero never gets old.',
    image: '/examples/superhero.jpg',
    tags: ['superhero', 'comic', 'marvel', 'dc', 'hero'],
    metaTitle: 'Superhero AI Filter — Comic Book Hero Style | MyMeme',
    metaDescription: 'Transform your photo into a comic book superhero. Bold styling, dynamic aesthetic. AI-powered, instant. Try free!',
    faqs: [
      { q: 'Will I get a specific superhero look?', a: 'The AI creates an original superhero aesthetic inspired by comic book art — bold colours, dynamic styling, and heroic composition. It\'s uniquely you.' },
      { q: 'Is it good for kids?', a: 'Kids absolutely love it! Seeing themselves as a superhero is a magical experience. Makes great bedroom wall art too.' },
      { q: 'Can I choose my superpower?', a: 'The AI creates the visual style automatically. For specific elements, try adding details in the optional job title or accessories fields.' },
      { q: 'Does it work with pet photos?', a: 'Super-pets are a thing! Your dog or cat will look heroic.' },
    ],
  },
  {
    id: 'clay-3d',
    name: 'Claymation',
    slug: 'clay-3d',
    emoji: '🧊',
    description: 'Sculpted clay figure look',
    longDescription: 'Transform into a charming claymation character, like something straight out of Wallace & Gromit or a stop-motion film. Smooth, sculpted textures, warm studio lighting, and an irresistibly tactile quality that makes everyone smile.',
    image: '/examples/clay-3d.jpg',
    tags: ['claymation', 'clay', '3d', 'stop motion', 'sculpted'],
    metaTitle: 'Claymation AI Filter — Clay Figure Style Photos | MyMeme',
    metaDescription: 'Turn photos into adorable claymation characters. Sculpted clay look, stop-motion charm. AI-powered, instant. Try free!',
    faqs: [
      { q: 'What is Claymation style?', a: 'Inspired by stop-motion animation like Wallace & Gromit, this style gives your photo a sculpted clay texture, warm studio lighting, and a charming, tactile quality.' },
      { q: 'Does it look realistic?', a: 'It\'s designed to look like a real clay figure — smooth textures, subtle imperfections, and warm lighting give it an authentic handcrafted feel.' },
      { q: 'Is it popular?', a: 'Claymation is one of our most shareable styles. People love the unique, artistic look and it performs incredibly well on social media.' },
      { q: 'Can I print it?', a: 'Yes! The HD output prints beautifully and makes a unique piece of wall art or a fun gift.' },
    ],
  },
  {
    id: 'pencil-sketch',
    name: 'Pencil Sketch',
    slug: 'pencil-sketch',
    emoji: '✏️',
    description: 'Hand-drawn pencil artistry',
    longDescription: 'The timeless elegance of a hand-drawn pencil sketch. Fine lines, careful shading, and the intimate quality of traditional drawing. Your photo becomes a beautiful piece of graphite art that looks like it was sketched by a portrait artist.',
    image: '/examples/pencil-sketch.jpg',
    tags: ['pencil', 'sketch', 'drawing', 'graphite', 'hand-drawn'],
    metaTitle: 'Pencil Sketch AI Filter — Hand-Drawn Portrait Style | MyMeme',
    metaDescription: 'Transform photos into beautiful pencil sketches with AI. Fine lines, careful shading, hand-drawn quality. Instant. Try free!',
    faqs: [
      { q: 'Does it look hand-drawn?', a: 'Yes! The AI replicates the fine lines, cross-hatching, and careful shading of a professional pencil portrait artist.' },
      { q: 'Is it black and white only?', a: 'The pencil sketch style is primarily monochrome — graphite grey tones that give it an authentic hand-drawn look.' },
      { q: 'Is it good for memorial portraits?', a: 'Pencil sketches are a beautiful, respectful way to create memorial portraits from old photos.' },
      { q: 'Can I use it for my portfolio?', a: 'Many artists and creatives use pencil sketch transformations as reference material or portfolio pieces.' },
    ],
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    slug: 'comic-book',
    emoji: '💬',
    description: 'Action comic panel style',
    longDescription: 'POW! BAM! Transform your photo into a dynamic comic book panel. Bold ink outlines, halftone dots, vibrant flat colours, and the kinetic energy of a comic book page. Perfect for anyone who\'s ever dreamed of being in a comic.',
    image: '/examples/comic-book.jpg',
    tags: ['comic', 'comic book', 'ink', 'halftone', 'action'],
    metaTitle: 'Comic Book AI Filter — Action Comic Style Photos | MyMeme',
    metaDescription: 'Turn photos into dynamic comic book art. Bold outlines, halftone dots, vibrant colours. AI-powered, instant. Try free!',
    faqs: [
      { q: 'How is it different from Superhero?', a: 'Comic Book focuses on the art style — bold ink lines, halftone dots, flat colours. Superhero adds the heroic costume and pose aesthetic on top.' },
      { q: 'Does it add speech bubbles?', a: 'The current style focuses on the visual transformation. You can add speech bubbles afterwards in any image editor!' },
      { q: 'What comic style is it?', a: 'It\'s inspired by classic American comics — think Marvel and DC\'s golden age art style with modern colour vibrancy.' },
      { q: 'Is it good for profile pictures?', a: 'Comic book style profile pictures stand out brilliantly on social media. Bold, colourful, and unique.' },
    ],
  },
  {
    id: 'sticker',
    name: 'Sticker',
    slug: 'sticker',
    emoji: '🏷️',
    description: 'Die-cut sticker vibes',
    longDescription: 'Turn yourself into a cool die-cut sticker. Clean outlines, bold colours, and that satisfying sticker aesthetic. Perfect for Telegram sticker packs, WhatsApp stickers, or just a fun, shareable image.',
    image: '/examples/sticker.jpg',
    tags: ['sticker', 'die-cut', 'telegram', 'whatsapp', 'cute'],
    metaTitle: 'Sticker AI Filter — Die-Cut Sticker Style Photos | MyMeme',
    metaDescription: 'Transform photos into cool die-cut stickers. Perfect for Telegram, WhatsApp. Clean, bold, shareable. AI-powered. Try free!',
    faqs: [
      { q: 'Can I use it for actual stickers?', a: 'Yes! The clean outlines and bold style are perfect for printing as real stickers or using as Telegram/WhatsApp sticker packs.' },
      { q: 'Does it have a transparent background?', a: 'The AI creates a sticker-style image with a clean, bordered look. For transparent backgrounds, you\'d need to remove the background separately.' },
      { q: 'Is it good for branding?', a: 'Sticker-style portraits make fun, recognisable personal branding elements — great for content creators and influencers.' },
      { q: 'What makes it different from Caricature?', a: 'Sticker style is cleaner and more graphic, with crisp outlines and bold flat colours. Caricature is more playful with exaggerated features.' },
    ],
  },
  {
    id: 'retro-80s',
    name: 'Retro 80s',
    slug: 'retro-80s',
    emoji: '🕹️',
    description: 'Synthwave nostalgia',
    longDescription: 'Radical! Step back into the 1980s with neon grids, sunset gradients, and synthwave aesthetics. Chrome text energy, VHS vibes, and the unmistakable glow of retro-futurism. Perfect for anyone who loves synthwave, vaporwave, or just misses the \'80s.',
    image: '/examples/retro-80s.jpg',
    tags: ['retro', '80s', 'synthwave', 'vaporwave', 'neon', 'nostalgia'],
    metaTitle: 'Retro 80s AI Filter — Synthwave Style Photos | MyMeme',
    metaDescription: 'Transform photos into radical 80s synthwave art. Neon grids, sunset gradients, retro vibes. AI-powered, instant. Try free!',
    faqs: [
      { q: 'What is the Retro 80s style?', a: 'Inspired by synthwave and vaporwave aesthetics, this style features neon grid lines, sunset gradients, chrome effects, and the glowing retro-futuristic look of 1980s pop culture.' },
      { q: 'How is it different from Cyberpunk?', a: 'Retro 80s is warmer with sunset oranges, pinks, and purples — nostalgic and fun. Cyberpunk is cooler and darker with blue-green neon — more gritty and futuristic.' },
      { q: 'Is it good for music content?', a: 'Perfect! Synthwave-style portraits are hugely popular for album covers, playlist covers, and music-related social content.' },
      { q: 'Can I use it for event posters?', a: 'Absolutely! The bold, eye-catching aesthetic works brilliantly for party invitations, event posters, and promotional material.' },
    ],
  },
]

export function getStyleBySlug(slug: string): StyleConfig | undefined {
  return styles.find((s) => s.slug === slug)
}

export function getAllStyleSlugs(): string[] {
  return styles.map((s) => s.slug)
}
